const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function batchHTML(p,s,i){
const rows=(s.rules||'').split('\n').filter(Boolean).map(x=>{const [a,...b]=x.split('|');return {a:e(a.trim()),b:e(b.join('|').trim())};});
let v='';
if(s.art==='batch-map')v=`<div class="b-map"><div class="b-circle"></div>${rows.map((r,n)=>`<div class="b-node n${n}"><small>0${n+1}</small><strong>${r.a}</strong><p>${r.b}</p></div>`).join('')}<div class="b-map-mark">ONE QUESTION<br>ONE CONTENT</div></div>`;
if(s.art==='batch-compare')v=`<div class="b-compare">${rows.map((r,n)=>`<section class="compare-${n}"><label>${n?'AFTER':'BEFORE'} / ${r.a}</label><p>${r.b}</p></section>${n===0?'<div class="b-down">↓ <span>구체적인 상황과 설명으로</span></div>':''}`).join('')}</div>`;
if(s.art==='batch-sequence')v=`<div class="b-sequence">${rows.map((r,n)=>`<section><div class="b-count">0${n+1}</div><div><strong>${r.a}</strong><p>${r.b}</p></div>${n<rows.length-1?'<span class="b-next">↓</span>':''}</section>`).join('')}</div><div class="b-seq-end">${e(s.sequenceEnd||'이 순서로, 한 편의 흐름을 만드세요.')}</div>`;
if(s.art==='batch-note')v=`<div class="b-note"><header><span>MONG PD / WORK NOTE</span><span>✎</span></header>${rows.map((r,n)=>`<div class="b-note-row"><small>0${n+1} · ${r.a}</small><p>${r.b}</p></div>`).join('')}<footer>설명은 구체적으로 · 확인한 사실에 맞게</footer></div>`;
if(s.art==='batch-check')v=`<div class="b-check"><div class="b-clip"></div><header>저장용 점검표 <span>CHECK / 03</span></header>${rows.map((r,n)=>`<section><span class="b-box">□</span><div><label>0${n+1} / ${r.a}</label><p>${r.b}</p></div></section>`).join('')}<footer>오늘 고칠 한 가지 <span>________________</span></footer></div>`;
if(s.art==='batch-follow')v=`<div class="b-follow-mark">↗</div><div class="b-follow-profile"><span>M</span><div><strong>@${e(p.instagram)}</strong><p>${e(s.profileLabel)}</p></div></div><div class="b-follow-button">팔로우 +</div><p class="b-follow-note">${e(s.closing)}</p>`;
if(s.art==='batch-summary')v=`<div class="b-summary">${rows.map((r,n)=>`<section><span>0${n+1}</span><div><strong>${r.a}</strong><p>${r.b}</p></div><b>↗</b></section>`).join('')}</div><div class="b-save"><span>↳</span><p>${e(s.closing)}</p><small>SAVE<br>FOR LATER</small></div>`;
return `<article class="card crafted batch ${s.art} ${p.ratio}"><div class="craft-top"><b>◆ ${e(p.brand)}</b><span>${e(p.series)} / ${String(i+1).padStart(2,'0')}</span></div><div class="card-content craft-content"><div class="craft-kicker">${e(s.eyebrow)}</div><h2>${e(s.title).replace(/\*\*(.+?)\*\*/gs,'<em>$1</em>')}</h2><p class="craft-lead">${e(s.body)}</p>${v}</div><div class="craft-footer"><span>@${e(p.instagram)}</span><span>0${i+1} — 0${p.slides.length}</span></div></article>`;
}
