const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const inquiryLayouts=['dm-cover','hesitation','cta-rewrite','reply-preview','one-path','cta-check','cta-summary'];
export function inquiryHTML(p,s,i){
const rows=(s.rules||'').split('\n').filter(Boolean).map(x=>{const [a,...b]=x.split('|');return [e(a.trim()),e(b.join('|').trim())];});
const r=n=>rows[n]||['',''];let v='';
if(s.art==='dm-cover')return `<article class="card crafted inquiry art-dm-cover ${p.ratio}"><div class="craft-top"><b>◆ ${e(p.brand)}</b><span>CONTENT CLINIC / 02</span></div><div class="card-content craft-content"><div class="cover-topic">${e(s.eyebrow)}</div><h1>${e(s.title).replace(/\*\*(.+?)\*\*/gs,'<em>$1</em>')}</h1>${s.image?`<div class="cover-photo-scene"><img src="${e(s.image)}" alt="휴대폰 메시지를 쓰다가 멈춘 손"><div class="photo-dm"><small>아직 보내지 않은 메시지</small><p>안녕하세요, 혹시…<i></i></p><span>↑</span></div><div class="photo-thought">“뭐라고 보내야 하지?”</div></div>`:`<div class="cover-chat"><div class="cover-chat-head"><div class="cover-avatar">M</div><div><b>MONG PD</b><small>콘텐츠를 보고 열린 대화창</small></div><span>···</span></div><div class="cover-received">문의는 DM 주세요.<span>↙</span></div><div class="cover-draft"><small>아직 보내지 않은 메시지</small><p>안녕하세요, 혹시…<i></i></p><div class="cover-send">↑</div></div><div class="cover-hesitate">“뭐라고 보내야 하지?”</div></div>`}<div class="cover-bottom"><span>첫 메시지를 쉽게 만드는<br><b>문의 안내의 3가지 기준</b></span><div>넘겨보기 <b>→</b></div></div></div><div class="craft-footer"><span>@${e(p.instagram)}</span><span>01 — 07</span></div></article>`;

if(s.art==='hesitation')v=`<div class="dm-scene"><div class="dm-head">문의하기 <span>↗</span></div><div class="dm-bubble">궁금한 점은 DM 주세요.</div><div class="thoughts">${rows.map((x,n)=>`<div><small>0${n+1}</small><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')}</div><div class="typing">메시지 입력… <span>│</span></div></div>`;
if(s.art==='cta-rewrite')v=`<div class="cta-before"><small>${r(0)[0]}</small><p>${r(0)[1]}</p><span>범위가 너무 넓습니다</span></div><div class="change-arrow">↓ <small>첫 메시지의 빈칸을 줄이면</small></div><div class="cta-after"><small>${r(1)[0]}</small><p>${r(1)[1]}</p></div><div class="micro-note">가상 예시 · 실제로 제공할 수 있는 안내만 약속하세요.</div>`;
if(s.art==='reply-preview')v=`<div class="reply-phone"><div class="phone-notch"></div><div class="chat-head">MONG PD <span>메시지</span></div><div class="chat-out">${r(0)[1]}</div><div class="chat-label">이렇게 안내할 수 있다면</div><div class="chat-in">${r(1)[1]}</div><div class="reply-items">${rows.slice(2).map(x=>`<div><span>✓</span><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')}</div><div class="chat-foot">상담 진행 예시 · 운영 방식에 맞게 조정</div></div>`;
if(s.art==='one-path')v=`<div class="path-map"><div class="path-origin">영상 마지막 5초</div><div class="path-split"><span>전화</span><span>링크</span><span>댓글</span><span>DM</span></div><div class="path-cross">한꺼번에 안내하면, 선택부터 해야 합니다.</div><div class="path-arrow">↓</div>${rows.map((x,n)=>`<div class="path-stop"><span>0${n+1}</span><div><b>${x[0]}</b><p>${x[1]}</p></div>${n<2?'<strong>↓</strong>':''}</div>`).join('')}</div>`;
if(s.art==='cta-check')v=`<div class="audit-sheet"><div class="audit-head">게시 전 / CTA 점검 <span>3 CHECKS</span></div>${rows.map((x,n)=>`<div class="audit-row"><span>□</span><div><small>CHECK 0${n+1}</small><b>${x[0]}</b><p>${x[1]}</p></div></div>`).join('')}<div class="audit-foot">최근 영상 한 편의 마지막 문장을 읽어보세요.</div></div>`;
if(s.art==='cta-summary')v=`<div class="formula">${rows.map((x,n)=>`<div><span>0${n+1}</span><b>${x[0]}</b><p>${x[1]}</p></div>`).join('<i>+</i>')}</div><div class="summary-cta"><small>오늘 바꿀 한 문장</small><p>${e(s.closing)}</p><b>저장하고, 다음 영상에 적용하세요. ↗</b></div>`;
return `<article class="card crafted inquiry art-${s.art} ${p.ratio}"><div class="craft-top"><b>◆ ${e(p.brand)}</b><span>CONTENT CLINIC 02 / ${String(i+1).padStart(2,'0')}</span></div><div class="card-content craft-content"><div class="craft-kicker">${e(s.eyebrow)}</div><h2>${e(s.title).replace(/\*\*(.+?)\*\*/gs,'<em>$1</em>')}</h2><p class="craft-lead">${e(s.body)}</p>${v}</div><div class="craft-footer"><span>@${e(p.instagram)}</span><span>${String(i+1).padStart(2,'0')} — ${String(p.slides.length).padStart(2,'0')}</span></div></article>`;
}
